# One-click installer for Windows (run install_windows.bat, which launches this).
#
# What it does:
#   1. Finds Python 3.10+ (installs Python 3.12 via winget if missing)
#   2. Creates the virtual environment and installs server dependencies
#   3. Optionally installs the ML (auto-annotation) dependencies
#   4. Generates backend\.env with a fresh secret key (SQLite by default)
#   5. Builds the frontend if needed (installs Node.js via winget if missing)
#   6. Opens TCP port 8000 in Windows Firewall (when run as Administrator)
#   7. Optionally registers a Scheduled Task so the server starts with Windows
#
# Parameters (all optional):
#   -WithML        install ML dependencies without asking
#   -NoML          skip ML dependencies without asking
#   -AutoStart     register the start-with-Windows scheduled task
#   -Port 8000     port to use for firewall rule / shortcuts
param(
    [switch]$WithML,
    [switch]$NoML,
    [switch]$AutoStart,
    [int]$Port = 8000
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

function Step($msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Ok($msg) { Write-Host $msg -ForegroundColor Green }
function Warn($msg) { Write-Host $msg -ForegroundColor Yellow }

# Run a command given as a string like "py -3.12" or "python" with extra args.
function Invoke-Python([string]$command, [string[]]$extraArgs) {
    $parts = $command.Split(" ")
    $exe = $parts[0]
    $baseArgs = @()
    if ($parts.Length -gt 1) { $baseArgs = $parts[1..($parts.Length - 1)] }
    & $exe @baseArgs @extraArgs
}

Write-Host "GraphMind (NER & RE annotation for knowledge graphs) - Windows installer" -ForegroundColor White
Write-Host "Install location: $Root"

# ---------- 1. Python ----------
Step "Locating Python 3.10+"
$python = $null
foreach ($candidate in @("py -3.12", "py -3.11", "py -3.10", "py -3", "python")) {
    try {
        $ver = Invoke-Python $candidate @("-c", "import sys; print('%d.%d' % sys.version_info[:2])") 2>$null
        if ($ver -and [version]$ver -ge [version]"3.10") { $python = $candidate; break }
    } catch { }
}
if (-not $python) {
    Warn "Python 3.10+ not found."
    if (Get-Command winget -ErrorAction SilentlyContinue) {
        Step "Installing Python 3.12 via winget"
        winget install --id Python.Python.3.12 -e --accept-source-agreements --accept-package-agreements
        $env:Path = [Environment]::GetEnvironmentVariable("Path", "Machine") + ";" +
                    [Environment]::GetEnvironmentVariable("Path", "User")
        $python = "py -3.12"
    } else {
        Write-Error "Install Python 3.12 from https://python.org (check 'Add python.exe to PATH'), then re-run."
    }
}
Ok "Using: $python"

# ---------- 2. Backend dependencies ----------
Step "Creating virtual environment and installing server dependencies"
if (-not (Test-Path "backend\.venv")) {
    Invoke-Python $python @("-m", "venv", "backend\.venv")
}
# Use the venv's python for all pip work: upgrading pip via pip.exe directly
# fails on Windows ("Access is denied") because the running exe is locked.
$py = "backend\.venv\Scripts\python.exe"
& $py -m pip install --quiet --upgrade pip
& $py -m pip install --quiet -r backend\requirements.txt
Ok "Server dependencies installed."

# ---------- 3. ML dependencies ----------
$installML = $false
if ($WithML) { $installML = $true }
elseif (-not $NoML) {
    $answer = Read-Host "`nInstall auto-annotation + relation-rule ML deps (spaCy, PyTorch, transformers, sentence-transformers, ~2.5 GB)? [y/N]"
    if ($answer -match "^[yY]") { $installML = $true }
}
if ($installML) {
    Step "Installing ML dependencies (this can take several minutes)"
    $gpu = Get-CimInstance Win32_VideoController -ErrorAction SilentlyContinue |
           Where-Object { $_.Name -match "NVIDIA" }
    if ($gpu) {
        Ok "NVIDIA GPU detected ($($gpu[0].Name)) - installing CUDA build of PyTorch"
        & $py -m pip install torch --index-url https://download.pytorch.org/whl/cu121
    }
    & $py -m pip install -r backend\requirements-ml.txt
    Ok "ML dependencies installed."
} else {
    Warn "Skipping ML dependencies. Install later with:"
    Warn "  backend\.venv\Scripts\python -m pip install -r backend\requirements-ml.txt"
}

# ---------- 4. Configuration ----------
Step "Configuring"
if (-not (Test-Path "backend\.env")) {
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $secret = ($bytes | ForEach-Object { $_.ToString("x2") }) -join ""
    # Absolute DB path (forward slashes) so the database is the same regardless
    # of which directory the server is launched from.
    $absDb = (Join-Path $Root "backend\annotation.db") -replace '\\', '/'
    @"
# Generated by install_windows.ps1 - see backend\.env.example for all options.
# For PostgreSQL (recommended for teams), change DATABASE_URL to:
#   postgresql+psycopg2://annotator:PASSWORD@localhost:5432/annotation
DATABASE_URL=sqlite:///$absDb
SECRET_KEY=$secret
"@ | Set-Content -Encoding ASCII backend\.env
    Ok "Created backend\.env (SQLite database, generated secret key)."
} else {
    Ok "backend\.env already exists - keeping it."
}

# ---------- 5. Frontend ----------
if (-not (Test-Path "backend\static\index.html")) {
    Step "Building frontend"
    if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
        if (Get-Command winget -ErrorAction SilentlyContinue) {
            Step "Installing Node.js LTS via winget"
            winget install --id OpenJS.NodeJS.LTS -e --accept-source-agreements --accept-package-agreements
            $env:Path = [Environment]::GetEnvironmentVariable("Path", "Machine") + ";" +
                        [Environment]::GetEnvironmentVariable("Path", "User")
        } else {
            Write-Error "Node.js is required to build the frontend. Install from https://nodejs.org and re-run."
        }
    }
    Push-Location frontend
    npm install --no-fund --no-audit
    npm run build
    Pop-Location
    Ok "Frontend built into backend\static."
} else {
    Step "Frontend already built - skipping (delete backend\static to rebuild)"
}

# ---------- 6. Firewall ----------
Step "Configuring Windows Firewall (port $Port)"
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
           ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if ($isAdmin) {
    if (-not (Get-NetFirewallRule -DisplayName "GraphMind Server" -ErrorAction SilentlyContinue)) {
        New-NetFirewallRule -DisplayName "GraphMind Server" -Direction Inbound `
            -Protocol TCP -LocalPort $Port -Action Allow | Out-Null
        Ok "Inbound firewall rule added for TCP $Port."
    } else {
        Ok "Firewall rule already exists."
    }
} else {
    Warn "Not running as Administrator - skipped the firewall rule."
    Warn "Other machines won't reach the server until you allow TCP $Port"
    Warn "(re-run this installer as Administrator, or add the rule manually)."
}

# ---------- 7. Start with Windows (optional) ----------
$startBat = Join-Path $Root "start_server.bat"
if ($AutoStart -or ((Read-Host "`nStart the server automatically when Windows boots? [y/N]") -match "^[yY]")) {
    if ($isAdmin) {
        schtasks /Create /F /TN "GraphMind Server" /SC ONSTART /RU SYSTEM `
            /TR "`"$startBat`"" | Out-Null
        Ok "Scheduled task created - the server starts with Windows."
    } else {
        Warn "Administrator rights required for the scheduled task - skipped."
    }
}

# ---------- Done ----------
$hostname = $env:COMPUTERNAME
Write-Host ""
Ok "Installation complete."
Write-Host ""
Write-Host "Start the server now:   start_server.bat   (or reboot if auto-start was enabled)"
Write-Host "Open on this machine:   http://localhost:$Port"
Write-Host "Open from the network:  http://${hostname}:$Port"
Write-Host "First visit:            click 'First time setup: create admin account'"
