#!/bin/bash
# One-step installer for macOS (Apple Silicon M1-M4 and Intel).
#
# Usage:
#   ./install_mac.sh             interactive (asks about ML dependencies)
#   ./install_mac.sh --with-ml   also install auto-annotation deps (spaCy/torch)
#   ./install_mac.sh --no-ml     skip auto-annotation deps
#
# After installing, start the server by double-clicking start_server.command
# or running:  ./start_server.command
set -euo pipefail
cd "$(dirname "$0")"

WITH_ML="ask"
for arg in "$@"; do
  case "$arg" in
    --with-ml) WITH_ML="yes" ;;
    --no-ml) WITH_ML="no" ;;
  esac
done

bold() { printf "\033[1m%s\033[0m\n" "$1"; }
step() { printf "\n\033[1;34m==>\033[0m \033[1m%s\033[0m\n" "$1"; }

bold "GraphMind (NER & RE annotation for knowledge graphs) — macOS installer"

# --- 1. Find a suitable Python (prefer 3.12/3.11/3.10) ---
step "Locating Python"
# Explicitly require Python 3.12 (then 3.11/3.10 as fallbacks). We search PATH
# *and* the standard python.org / Homebrew install locations, because the bare
# `python3` on macOS is usually the old system 3.9 — which we deliberately
# avoid (it pins spaCy to the legacy 3.7.x line).
find_python() {
  ver="$1"
  for c in \
    "python$ver" \
    "/Library/Frameworks/Python.framework/Versions/$ver/bin/python$ver" \
    "/opt/homebrew/bin/python$ver" \
    "/opt/homebrew/opt/python@$ver/bin/python$ver" \
    "/usr/local/bin/python$ver"; do
    if command -v "$c" >/dev/null 2>&1; then
      command -v "$c"
      return 0
    fi
    [ -x "$c" ] && { echo "$c"; return 0; }
  done
  return 1
}

PY=""
for ver in 3.12 3.11 3.10; do
  if PY="$(find_python "$ver")"; then break; fi
  PY=""
done
if [ -z "$PY" ]; then
  echo "Python 3.12 was not found (the macOS system python3 is 3.9, which we don't use)."
  echo "Install Python 3.12, then re-run this installer:"
  echo "    brew install python@3.12      # Homebrew — https://brew.sh"
  echo "    or download from https://www.python.org/downloads/macos/"
  exit 1
fi
PYVER="$("$PY" -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')"
echo "Using $PY (Python $PYVER)"

# --- 2. Backend virtual environment + dependencies ---
step "Installing backend dependencies"
# Rebuild an existing environment if it was created with an older Python
# (e.g. a stale 3.9 venv), so a re-run actually upgrades the interpreter.
if [ -d backend/.venv ]; then
  VENV_TOO_OLD="$(backend/.venv/bin/python -c 'import sys; print(int(sys.version_info[:2] < (3, 10)))' 2>/dev/null || echo 1)"
  if [ "$VENV_TOO_OLD" = "1" ]; then
    VENV_VER="$(backend/.venv/bin/python -c 'import sys; print("%d.%d" % sys.version_info[:2])' 2>/dev/null || echo unknown)"
    echo "Existing backend/.venv uses Python $VENV_VER (< 3.10) — rebuilding with Python $PYVER."
    rm -rf backend/.venv
  fi
fi
if [ ! -d backend/.venv ]; then
  "$PY" -m venv backend/.venv
fi
backend/.venv/bin/pip install --quiet --upgrade pip
backend/.venv/bin/pip install --quiet -r backend/requirements.txt
echo "Backend dependencies installed."

# --- 3. Optional ML dependencies (auto-annotation) ---
if [ "$WITH_ML" = "ask" ]; then
  printf "\nInstall auto-annotation + relation-rule ML deps (spaCy, PyTorch,\ntransformers, sentence-transformers, ~2 GB)? [y/N] "
  read -r answer
  case "$answer" in [yY]*) WITH_ML="yes" ;; *) WITH_ML="no" ;; esac
fi
if [ "$WITH_ML" = "yes" ]; then
  step "Installing ML dependencies (this can take a few minutes)"
  backend/.venv/bin/pip install --quiet -r backend/requirements-ml.txt
  echo "ML dependencies installed. Training will use the Apple GPU (MPS) automatically."
else
  echo "Skipping ML dependencies. Install later with:"
  echo "  backend/.venv/bin/pip install -r backend/requirements-ml.txt"
fi

# --- 4. Configuration (.env with a fresh secret key) ---
step "Configuring"
if [ ! -f backend/.env ]; then
  SECRET="$(backend/.venv/bin/python -c 'import secrets; print(secrets.token_hex(32))')"
  # Absolute DB path so the database is the same no matter which directory the
  # server is launched from.
  ABS_DB="$(cd backend && pwd)/annotation.db"
  cat > backend/.env <<EOF
# Generated by install_mac.sh — see backend/.env.example for all options.
DATABASE_URL=sqlite:///$ABS_DB
SECRET_KEY=$SECRET
EOF
  echo "Created backend/.env (SQLite database, generated secret key)."
else
  echo "backend/.env already exists — keeping it."
fi

# --- 5. Frontend (build only if not already built) ---
if [ ! -f backend/static/index.html ]; then
  step "Building frontend"
  if ! command -v npm >/dev/null 2>&1; then
    echo "Node.js is required to build the frontend. Install it with:"
    echo "  brew install node    (or download from https://nodejs.org)"
    echo "Then re-run this installer."
    exit 1
  fi
  (cd frontend && npm install --no-fund --no-audit && npm run build)
  echo "Frontend built into backend/static."
else
  step "Frontend already built — skipping (delete backend/static to rebuild)"
fi

chmod +x start_server.command 2>/dev/null || true

printf "\n"
bold "✅ Installation complete."
echo
echo "Start the server:   double-click start_server.command, or run ./start_server.command"
echo "Then open:          http://localhost:8000"
echo "First visit:        click 'First time setup: create admin account'"
echo
echo "To make the server reachable by others on your network, your Mac's"
echo "hostname works too:  http://$(scutil --get LocalHostName 2>/dev/null || hostname).local:8000"
